runtime: custom
env: flex

runtime_config:
  jdk: openjdk9

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always
    redirect_http_response_code: 301
manual_scaling:
  instances: 1

network:
  forwarded_ports:
    - 8445/tcp

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10